### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by advaith1** [NexInfinite/redpandapics#1]
redpanda.pics is 502ing
![image](https://user-images.githubusercontent.com/11778454/144398391-6a433efb-e135-4004-9d6e-d075a15a00b4.png)

**Comment by NexInfinite** [comment]
Hey,
Sorry for the incredibly long delay, I stopped paying for the domain a while ago and the site is now done. Currently cleaning up my GitHub and so stumbled across this 😅 
\- Julian
